trigger: none

resources:
  pipelines:
  - pipeline: buildPipeline
    source: 'Build Pipeline1'
    trigger: true

pool:
  vmImage: 'windows-latest'

steps:

- checkout: none

- download: buildPipeline
  displayName: 'Download Build Artifacts'
  artifact: 'NZWalks'

- task: PowerShell@2
  displayName: 'Deploy Application'
  inputs:
    targetType: 'inline'
    script: |
      $PackagePath = "$(Pipeline.Workspace)\buildPipeline\NZWalks\s"

      Write-Host "Deployment Started"

      if (Test-Path $PackagePath) {
        Write-Host "Artifact Verified"
        Write-Host "Deployment Completed Successfully"
      }
      else {
        throw "Artifact Not Found"
      }