trigger:
- master

pool:
  vmImage: 'ubuntu-22.04'

steps:

- task: UseDotNet@2
  name: InstallDotNet
  displayName: 'Install .NET SDK 8.0'
  inputs:
    packageType: 'sdk'
    version: '8.0.425'

- task: DotNetCoreCLI@2
  name: Restore
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: 'NZWalks.sln'

- task: DotNetCoreCLI@2
  name: Build
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: 'NZWalks.sln'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  name: Publish
  displayName: 'Publish Application'
  inputs:
    command: 'publish'
    projects: 'NZWalks.sln'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  name: PublishArtifacts
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'NZWalks'
    publishLocation: 'Container'