trigger: none

resources:
  pipelines:
  - pipeline: buildPipeline
    source: 'Build Pipeline1'
    trigger: true

pool:
  vmImage: 'windows-latest'

steps:

- download: buildPipeline
  artifact: NZWalks

- powershell: |
    Write-Host "Deployment Started"
    Get-ChildItem "$(Pipeline.Workspace)" -Recurse
  displayName: "Verify Artifact"